### ISSUE TITLE
Touch area sensitivity calibration

### ISSUE THREAD

**Issue by EdHiro** [LingFeng-bbben/MajdataPlay#14]
某些时候触摸会挂 需要本体启动一次才恢复正常 可能是未进行触摸灵敏度校准导致的

**Comment by LingFeng-bbben** [comment]
Please provide more info about the COM communication.

**Comment by LingFeng-bbben** [comment]
confirmed

**Comment by LingFeng-bbben** [comment]
see https://github.com/Sucareto/Mai2Touch/tree/main/Mai2Touch
