### ISSUE TITLE
More custom settings

### ISSUE THREAD

**Issue by LeZi9916** [LingFeng-bbben/MajdataPlay#18]
## PlanTo
- Offset
   - ~~AudioOffset~~
   - ~~DisplayOffset~~
   - JudgeOffset
- JudgeDisplayOption
   - FastLate                // boolean
   - FastLateType        // All , BelowCP , BelowP , BelowGR , BelowGD
   - NoteJudge            
   - NoteJudgeType   
   - TouchJudge    
   - TouchJudgeType 
   - SlideJudge 
   - SlideJudgeType
   - DisplayDistance  // float: 1.0 - 0.5

**Comment by LingFeng-bbben** [comment]
DisplayDistance 是虾米

**Comment by LeZi9916** [comment]
> DisplayDistance 是虾米
是JudgeEffect与边界的距离，越小越靠近原点
我计划用百分比表示，0.5就是1号键与原点连线上的中点

**Comment by LeZi9916** [comment]
finished in commit https://github.com/LingFeng-bbben/MajdataPlay/commit/d5a20195253ad061bc5ed4d77de40a837d48ad92
