### ISSUE TITLE
Audio breaking

### ISSUE THREAD

**Issue by QuinnC419** [LingFeng-bbben/MajdataPlay#35]
Audio not working 
显示音频错位，不知道修复方法，音质爆炸且断断续续
![IMG_20240916_133939](https://github.com/user-attachments/assets/e8c5d9dd-f7e1-42c5-9c35-873ec5d9235d)

**Comment by LingFeng-bbben** [comment]
调整一下你的asio驱动参数
或者试试使用unity backend
