### ISSUE TITLE
分辨率正确但两边有黑框

### ISSUE THREAD

**Issue by BenTease** [LingFeng-bbben/MajdataPlay#38]
![E5782186F892CA36A097FA81991DBEE0](https://github.com/user-attachments/assets/d161db2e-a1b8-45ba-a081-9246f90ee9ac)
查了一下发现好像是unity打包exe的问题

**Comment by LeZi9916** [comment]
> ![E5782186F892CA36A097FA81991DBEE0](https://private-user-images.githubusercontent.com/91461429/369662434-d161db2e-a1b8-45ba-a081-9246f90ee9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzg2NDMsIm5iZiI6MTcyNzA3ODM0MywicGF0aCI6Ii85MTQ2MTQyOS8zNjk2NjI0MzQtZDE2MWRiMmUtYTFiOC00NWJhLWEwODEtOTI0NmY5MGVlOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjkzYmViMTk3MmE4MTUwNDdmOWUxNWRiZTcxNmJiODM1ODc4YzllN2YwN2U2MjdkZjdlNzhlYzhkNTA4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ng9_SSA4rcMAm3fQlPXlNKJfz3fEOCo89y5L3x9pevA) 查了一下发现好像是unity打包exe的问题

分辨率是Auto还是自定义？

**Comment by LingFeng-bbben** [comment]
按两下alt+enter试试

**Comment by BenTease** [comment]
> > ![E5782186F892CA36A097FA81991DBEE0](https://private-user-images.githubusercontent.com/91461429/369662434-d161db2e-a1b8-45ba-a081-9246f90ee9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzg2NDMsIm5iZiI6MTcyNzA3ODM0MywicGF0aCI6Ii85MTQ2MTQyOS8zNjk2NjI0MzQtZDE2MWRiMmUtYTFiOC00NWJhLWEwODEtOTI0NmY5MGVlOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjkzYmViMTk3MmE4MTUwNDdmOWUxNWRiZTcxNmJiODM1ODc4YzllN2YwN2U2MjdkZjdlNzhlYzhkNTA4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ng9_SSA4rcMAm3fQlPXlNKJfz3fEOCo89y5L3x9pevA) 查了一下发现好像是unity打包exe的问题
> 
> 分辨率是Auto还是自定义？
> 

auto

**Comment by BenTease** [comment]
> 按两下alt+enter试试

周末回家试下❤️

**Comment by BenTease** [comment]
> 按两下alt+enter试试

神医
