### ISSUE TITLE
NAudio Leaking Memory

### ISSUE THREAD

**Issue by BenTease** [LingFeng-bbben/MajdataPlay#43]
~[Exception] NullReferenceException: Object reference not set to an instance of an object
Live2D.Cubism.Framework.MotionFade.CubismFadeStateObserver.OnStateEnter (UnityEngine.Animator animator, UnityEngine.AnimatorStateInfo stateInfo, System.Int32 layerIndex, UnityEngine.Animations.AnimatorControllerPlayable controller) (at <531fa183c67b42958b3c79dd0ba85867>:0)~

**Comment by LingFeng-bbben** [comment]
This will prob related to the Asio/WaveOut backend memory leak.
Although switching to Unity backend can work it around, the proposal for the fix are:

1.  Directly read the audio from file, no caching for the game music.
2. Switch to other Wrapper, such as BASS.net

**Comment by LeZi9916** [comment]
> 1. Directly read the audio from file, no caching for the game music.

finished in commit https://github.com/LingFeng-bbben/MajdataPlay/commit/259eab818b4c263649f97bdc61a05f2a73b93485

**Comment by LingFeng-bbben** [comment]
According to testing, the program will be ustable and drop fps when lot of songs have been played.
Current workaround is to restart the program.

**Comment by LingFeng-bbben** [comment]
> 2\. Switch to other Wrapper, such as BASS.net

solved in e2468b0
