### ISSUE TITLE
Break slide causing frame drop

### ISSUE THREAD

**Issue by LingFeng-bbben** [LingFeng-bbben/MajdataPlay#64]
![image](https://github.com/user-attachments/assets/96efbe3c-2cb4-45a0-a5c5-203dec850e37)

**Comment by LeZi9916** [comment]
我服了，这是套了多少层Slide

**Comment by LeZi9916** [comment]
![image](https://github.com/user-attachments/assets/4fb77aac-d3bd-48e6-ae3d-3601cc03a268)

**Comment by LeZi9916** [comment]
fixed in https://github.com/LingFeng-bbben/MajdataPlay/pull/88
